### ISSUE TITLE
TypeError: Module.load_state_dict() got an unexpected keyword argument 'assign'

### ISSUE THREAD

**Issue by BIGdeadLock** [urchade/GLiNER#29]
I'm getting the following error when trying to load the model:

![Screenshot 2024-03-19 at 9 56 55](https://github.com/urchade/GLiNER/assets/64005996/08d7e95f-472a-4e5c-bf83-b8211a99187d)

Running on databricks notebook.

**Comment by urchade** [comment]
removing the part "assign=True" in your source code should resolve the issue.

**Comment by urchade** [comment]
ok, try reinstall ```pip install gliner==0.1.3```

**Comment by BIGdeadLock** [comment]
Work, thanks!

**Comment by Marwen-Bhj** [comment]
hello @urchade I am using `gliner 0.1.4` and I am still facing this issue.

**Comment by ajayp** [comment]
I had similar issues running locally on my mac.   I ended up creating a virtual env. 

```
python3 -m venv myenv
source myenv/bin/activate
pip3 install gliner==0.1.3
pip3  install scipy==1.12 
python3 glinerSampleCode.py  
```

**Comment by urchade** [comment]
Upgrade to 0.1.7
